version: '2'

services:
  web:
    image: dabliu/web:v1.0.0
    command: bundle exec puma -e production -b unix:///tmp/sockets/web.sock
    environment:
      RAILS_ENV:         production
      DATABASE_HOST:     postgres
      DATABASE_PORT:     5432
      DATABASE_USER:     postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME:     dabliu_production
      SECRET_KEY_BASE:   VhmkcZPs65VjnYBTSzKyaUb2EktDrHnFTgbpMcfqGnxHjHTZsFJxzP5kSFEhSVJDXRUk8C7DgyErqd8T

  nginx:
    image: dabliu/nginx:v1.0.0
    environment:
      WEB_DOMAIN: 'dabliu.com.ar www.dabliu.com.ar'
      WEB_SOCKET_NAME: web
